### ISSUE TITLE
您好，请问后期能结合CICD来自动触发运行脚本不，界面直接选择执行时间？

### ISSUE THREAD

**Issue by cfy3133** [hui-huo/jmeter_report_server#1]
您好，请问后期能结合CICD来自动触发运行脚本不，界面直接选择执行时间？

**Comment by hui-huo** [comment]
感谢关注，实现CICD有两种：
1. 结合jenkins来触发，jmx脚步上传到linux服务器，使用命令jmeter -n来执行，jenkins可以设定触发周期和时间。
2. 界面选择执行，因目前也只做了报告收集的功能，暂没有对开发对测试脚步收集的功能，所以界面目前工作忙一点暂没有打算做...
