### ISSUE TITLE
请问能够获取到当前执行接口成功、失败的条数、以及占比吗？然后传递给webhook机器人

### ISSUE THREAD

**Issue by cfy3133** [hui-huo/jmeter_report_server#2]

**Comment by hui-huo** [comment]
可先看下目前已有的功能接口返回数据是否满足需求，不满足的话可以创建新的接口来获取想要的数据。

**Comment by hui-huo** [comment]
@cfy3133 
可先看下目前已有的功能接口返回数据是否满足需求，不满足的话可以创建新的接口来获取想要的数据。

**Comment by cfy3133** [comment]
好滴

**Comment by cfy3133** [comment]
好像需要传递一个参数确定是那个模块的用例跑完了，现在是没有这个参数只是给了个构建id，构建id不好判断需要的是那个模块的用例执行完成了，是否是今天的数据等等

**Comment by cfy3133** [comment]
![image](https://github.com/hui-huo/jmeter_report_server/assets/43978367/d994f885-b6a0-4941-81a8-6e46a109a861)

**Comment by hui-huo** [comment]
@cfy3133 加我下vx吧 _huihuo   记得备注下

**Comment by hui-huo** [comment]
看板页面有个最新构建的接口，你看下是否满足你的使用
@cfy3133 


<img width="737" alt="image" src="https://github.com/hui-huo/jmeter_report_server/assets/55521126/0064c9b0-3350-4770-b45c-e2066af94073">


curl 'http://1.116.137.209:8000/api/result/latest' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,und;q=0.7' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Cookie: csrftoken=tbK7uf8oyJHdgVMdujk9swUhzUD6qCjLaaJxJzy9OqQAiank2okHKe6xl2oKRKCK; lang=zh-CN; order=id%20desc; serverType=nginx; pro_end=-1; ltd_end=-1; memSize=1998; bt_user_info=%7B%22status%22%3Atrue%2C%22msg%22%3A%22%u83B7%u53D6%u6210%u529F%21%22%2C%22data%22%3A%7B%22username%22%3A%22185****7615%22%7D%7D; db_page_model=mysql; backup_path=/www/backup; i_like_gogs=2f66953466802b36; 872af80506f8f54aa58ba09de8adfd14=9f8c57c8-5305-4263-8057-69229fc872db.n0udvt-bLueNre1FV3nCro0jgT8' \
  -H 'Origin: http://1.116.137.209:8000' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://1.116.137.209:8000/dashboard' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --data-raw '{"project":"订单中心","env":"TEST"}' \
  --compressed \
  --insecure

**Comment by cfy3133** [comment]
好滴，非常感谢，满足，再次感谢
