### ISSUE TITLE
你好，请问被测项目名称、被测环境名称是怎么来的，我换了一个项目名称、环境名称就无法推送到数据了，尴尬

### ISSUE THREAD

**Issue by cfy3133** [hui-huo/jmeter_report_server#5]

**Comment by hui-huo** [comment]
![image](https://github.com/hui-huo/jmeter_report_server/assets/55521126/514aa5b4-e506-4ffd-8ade-63ce262268c9)

在后端监听器的参数中配置

**Comment by cfy3133** [comment]
你好，是的，我配置了之后在测试环境是可以的，但是我把配置换成开发环境就不行了，不知道为啥，配置换了name、env为开发环境，然后jmeter中也是换了启用了开发环境的默认值，但是运行就无法推送数据了

**Comment by hui-huo** [comment]
能截图看下吗，另外把jmeter的日志打开后 执行一次测试，插件里有记录发送日志

**Comment by cfy3133** [comment]
![image](https://github.com/hui-huo/jmeter_report_server/assets/43978367/5ced961d-3482-401e-9ca7-64884fa2ecf4)
![image](https://github.com/hui-huo/jmeter_report_server/assets/43978367/9157294b-b72e-4537-a5f2-d27cd46aaeb5)
![image](https://github.com/hui-huo/jmeter_report_server/assets/43978367/93ca858c-f751-4b1e-af41-7277b22fdfa0)
所以很迷惑

**Comment by hui-huo** [comment]
@cfy3133 看你截图有些涉及隐私数据，删除一下吧，看日志是没有发送到服务端收集到，你加我vx一下吧`_huihuo`，  需要排查下

**Comment by cfy3133** [comment]
好的
