### ISSUE TITLE
当一个事务控制下面存在多个事务控制且发送的数据也会不正确

### ISSUE THREAD

**Issue by KnightBlood** [hui-huo/jmeter_report_server#7]
当一个事务控制下面存在多个事务控制且发送的数据也会不正确

**Comment by hui-huo** [comment]
能截图看下文件结构是什么样子吗，事务控制器的使用参考下MD文档说明（有一定的使用规则）

**Comment by KnightBlood** [comment]
给你个示意吧 测试是在内网执行的

![image](https://github.com/hui-huo/jmeter_report_server/assets/14256591/60553334-b93f-42e2-8704-6fad176a4024)

**Comment by KnightBlood** [comment]
![image](https://github.com/hui-huo/jmeter_report_server/assets/14256591/5a222988-9c26-4fd5-94e8-89c44a0356f5)

**Comment by KnightBlood** [comment]
数据上传后 页面就只显示 AA#-AA01
AA#-AA02,AA#-AA03就不显示了

**Comment by hui-huo** [comment]
好的，回去抽时间看下，看日志是正常的，AA#-AA03-AA03-01下的请求有显示吗

**Comment by KnightBlood** [comment]
> 好的，回去抽时间看下，看日志是正常的，AA#-AA03-AA03-01下的请求有显示吗

请求都在
都跑到AA#-AA01下去了

**Comment by KnightBlood** [comment]
看了下后端监听代码 发现是从顶层往下找的
是不是可以从取样器找父级
类似以下代码

SampleResult sampleResult = ctx.getPreviousResult();
String transactionControllerName = "";

while (sampleResult.getParent() != null && sampleResult.getParent() instanceof TransactionController) {
    sampleResult = sampleResult.getParent();
}

if (sampleResult.getParent() != null) {
    transactionControllerName = sampleResult.getParent().getSampleLabel();
}

**Comment by KnightBlood** [comment]
> 01下

![image](https://github.com/hui-huo/jmeter_report_server/assets/14256591/6108d6cf-2173-4b40-99a8-4b316f9e544c)

**Comment by KnightBlood** [comment]
> 好的，回去抽时间看下，看日志是正常的，AA#-AA03-AA03-01下的请求有显示吗

![image](https://github.com/hui-huo/jmeter_report_server/assets/14256591/da773665-a31c-4644-8a94-99604faa3e8e)
这样改

**Comment by hui-huo** [comment]
已修复 https://github.com/hui-huo/JMeter-Backend-Listener/releases/tag/v1.4
